# Generated by Django 5.1.7 on 2025-03-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.CharField(default='', max_length=255),
        ),
    ]
