# Generated by Django 5.1.7 on 2025-03-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_bookimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookImage',
        ),
    ]
