# Generated by Django 5.1.7 on 2025-03-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_bookimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookImage',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
